### ISSUE TITLE
Error after successful Payment

### ISSUE THREAD

**Issue by eyeke04** [pauloladimeji/paystack-easy-digital-downloads#6]
Hello Paul,
After a successful payment, this is what shows. Please can you advice.

More details:
Plugin---- Easy Digital Download version 2.8.10
Theme---Jupiter theme  version 5.9.7
Wordpress --- latest version 

`Warning: array_key_exists() expects parameter 2 to be array, null given in /hermes/bosnacweb02/bosnacweb02ag/b159/ipg.uniadvanceinstitutec/books/wp-content/plugins/paystack-easy-digital-downloads-master/paystack-edd-gateway.php on line 322 Fatal error: Uncaught exception 'Exception' with message 'Invalid customer email associated with Transaction code:MH969897BH64XAA34893E93C-e9d73517-a260-432e-bf7d-bf5a3f3a0fca and Paystack reference: . Possible hack attempt.' in /hermes/bosnacweb02/bosnacweb02ag/b159/ipg.uniadvanceinstitutec/books/wp-content/plugins/paystack-easy-digital-downloads-master/paystack-edd-gateway.php:331 Stack trace: #0 [internal function]: EDD_Paystack->process_payment(Array) #1 /hermes/bosnacweb02/bosnacweb02ag/b159/ipg.uniadvanceinstitutec/books/wp-includes/class-wp-hook.php(298): call_user_func_array(Array, Array) #2 /hermes/bosnacweb02/bosnacweb02ag/b159/ipg.uniadvanceinstitutec/books/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array) #3 /hermes/bosnacweb02/bosnacweb02ag/b159/ipg.uniadvanceinstitutec/books/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #4 /hermes/bosnacweb02/bosnacweb02ag/b159/ipg.uniadvanceinstitutec/books/wp-content/plugins/easy-digital-downloads/includes/gateways/functions.php(308): do_action in /hermes/bosnacweb02/bosnacweb02ag/b159/ipg.uniadvanceinstitutec/books/wp-content/plugins/paystack-easy-digital-downloads-master/paystack-edd-gateway.php on line 331`
<img width="1122" alt="screen shot 2017-10-24 at 2 02 56 pm" src="https://user-images.githubusercontent.com/10612514/31944582-6f924ac0-b8c4-11e7-8f17-d8ba43fe7e4e.png">

**Comment by eyeke04** [comment]
So it turned out this error was because the person's IP was blocked and the response was a 403 Forbidden. @pauloladimeji this response can be handled better tho.
