### ISSUE TITLE
Transaction reference not found Error

### ISSUE THREAD

**Issue by steveamaza** [pauloladimeji/paystack-easy-digital-downloads#7]
When a user clicks the 'Click to Pay Online' button and then fills in their email and First Name, this button appears on clicking 'Pay Now'

`Fatal error: Uncaught exception 'Exception' with message 'Failed with message from Paystack: Transaction reference not found' in /home4/waeorg0aaxkm/public_html/wp-content/plugins/paystack-easy-digital-downloads-master/paystack-edd-gateway.php:328 Stack trace: #0 [internal function]: EDD_Paystack->process_payment(Array) #1 /home4/waeorg0aaxkm/public_html/wp-includes/class-wp-hook.php(298): call_user_func_array(Array, Array) #2 /home4/waeorg0aaxkm/public_html/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array) #3 /home4/waeorg0aaxkm/public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #4 /home4/waeorg0aaxkm/public_html/wp-content/plugins/easy-digital-downloads/includes/gateways/functions.php(308): do_action('edd_gateway_pay...', Array) #5 /home4/waeorg0aaxkm/public_html/wp-content/plugins/easy-digital-downloads/includes/process-purchase.php(171): edd_send_to_gateway('paystack', Array) #6 [internal function]: edd_process_purchase_form(Array) #7 /home4/waeorg0aaxkm/public_html/wp-includes/clas in /home4/waeorg0aaxkm/public_html/wp-content/plugins/paystack-easy-digital-downloads-master/paystack-edd-gateway.php on line 328`

<img width="1270" alt="screen shot 2017-11-03 at 7 24 16 pm" src="https://user-images.githubusercontent.com/15840315/32390093-56609bb8-c0cd-11e7-8d24-fc00831260c2.png">

If you need more information, let me know so I can furnish you with the details. 

Thank you

**Comment by eddy-bob** [comment]
i have the same problem in my  test 
paystack verification

**Comment by ProfNuru** [comment]
SOLVED
This error is as a result of a misunderstanding in the documentation. The verify transaction URL from the documentation is:
"https://api.paystack.co/transaction/verify/:reference"
Notice the colon (:) before the 'reference'. The error comes from appending the reference number to the URL without removing the colon.
So for a transaction with transaction number 12345, the URL should look like this
"https://api.paystack.co/transaction/verify/12345"
NOT
"https://api.paystack.co/transaction/verify/:12345"

**Comment by cyrilmano** [comment]
> SOLVED This error is as a result of a misunderstanding in the documentation. The verify transaction URL from the documentation is: "https://api.paystack.co/transaction/verify/:reference" Notice the colon (:) before the 'reference'. The error comes from appending the reference number to the URL without removing the colon. So for a transaction with transaction number 12345, the URL should look like this "https://api.paystack.co/transaction/verify/12345" NOT "https://api.paystack.co/transaction/verify/:12345"

Thank you @ProfNuru for this. And many developers would be experiencing this. I think @paystack should update the documentation. @steveamaza Hope you rectified it.

**Comment by yusuf-umarr** [comment]
> SOLVED This error is as a result of a misunderstanding in the documentation. The verify transaction URL from the documentation is: "https://api.paystack.co/transaction/verify/:reference" Notice the colon (:) before the 'reference'. The error comes from appending the reference number to the URL without removing the colon. So for a transaction with transaction number 12345, the URL should look like this "https://api.paystack.co/transaction/verify/12345" NOT "https://api.paystack.co/transaction/verify/:12345"

thanks @ProfNuru, you just saved my ass.
